name: Deploy Node.js App

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'  # Caches node_modules for faster builds

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci         # Clean install (uses package-lock.json)
          npm install dotenv  # Ensure dotenv is installed

      # Start server with environment variables
      - name: Start server
        run: npm start
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PLAID_ENV: ${{ secrets.PLAID_ENV }}
          