name: Deploy Node.js App

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Node.js with caching
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'  # Caches node_modules for faster builds

      # Install dependencies efficiently
      - name: Install dependencies
        run: |
          npm ci  # Clean install from lockfile (faster and more reliable)
          npm install dotenv  # Explicitly ensure dotenv is present

      # Start server with environment variables
      - name: Start server
        run: npm start
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PLAID_ENV: ${{ secrets.PLAID_ENV }}
          STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID}}